# Reconstructed initial schema for the public Budget Manager distribution.
# This matches the schema shipped before migrations 0002-0006.
import decimal
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner','Owner'),('member','Member'),('viewer','Viewer')], default='member', max_length=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='finance.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='EUR', max_length=3, validators=[RegexValidator('^[A-Za-z]{3}$','Use a 3-letter currency code such as EUR.')])),
                ('shift_late_funding', models.BooleanField(default=True)),
                ('shift_day', models.PositiveSmallIntegerField(default=27, validators=[MinValueValidator(1), MaxValueValidator(31)])),
                ('savings_rate_basis', models.CharField(choices=[('allocated','Savings allocated / funding'),('surplus','(Funding - expenses) / funding')], default='allocated', max_length=12)),
                ('week_starts_monday', models.BooleanField(default=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('checking','Checking'),('savings','Savings'),('cash','Cash'),('restricted','Restricted / blocked'),('credit','Credit card'),('loan','Loan'),('investment','Investment'),('asset','Other asset'),('external','External / outside tracked finances')], default='checking', max_length=16)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[RegexValidator('^[A-Za-z]{3}$','Use a 3-letter currency code such as EUR.')])),
                ('include_in_net_worth', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), help_text='Signed balance in the account currency; liabilities are negative.', max_digits=16)),
                ('opening_base_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Signed opening value in the household base currency. Required for non-base-currency accounts with a non-zero opening balance.', max_digits=16, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.household')),
            ],
            options={'ordering':['name']},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('funding','Funding'),('expense','Expense'),('savings','Savings')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.household')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category')),
            ],
            options={'ordering':['kind','sort_order','name']},
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='finance.household')),
            ],
            options={'ordering':['name']},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('income','Income'),('expense','Expense'),('transfer','Transfer'),('savings','Savings'),('release','Restricted-funds release'),('debt','Debt payment'),('adjustment','Balance adjustment'),('other','Other')], default='other', max_length=12)),
                ('status', models.CharField(choices=[('pending','Pending'),('cleared','Cleared'),('reconciled','Reconciled')], default='cleared', max_length=12)),
                ('description', models.CharField(max_length=240)),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('import_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.household')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='finance.tag')),
            ],
            options={'ordering':['-date','-id']},
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount in account currency.', max_digits=16)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Signed amount in household base currency; transaction base entries must sum to zero.', max_digits=16)),
                ('memo', models.CharField(blank=True, max_length=160)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.transaction')),
            ],
            options={'ordering':['id']},
        ),
        migrations.CreateModel(
            name='BudgetImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('funding','Funding available'),('expense','Expense'),('savings','Savings allocation')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[MinValueValidator(decimal.Decimal('0.00'))])),
                ('budget_date', models.DateField(db_index=True)),
                ('memo', models.CharField(blank=True, max_length=160)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_impacts', to='finance.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_impacts', to='finance.transaction')),
            ],
            options={'ordering':['budget_date','id']},
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='First day of budget month.')),
                ('amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=16, validators=[MinValueValidator(decimal.Decimal('0.00'))])),
                ('note', models.CharField(blank=True, max_length=160)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='finance.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='finance.household')),
            ],
            options={'ordering':['month','category__kind','category__sort_order','category__name']},
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[MinValueValidator(decimal.Decimal('0.01'))])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('starting_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='finance.account')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'kind':'savings'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(blank=True, max_length=120)),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=16, validators=[MinValueValidator(decimal.Decimal('0.01'))])),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, default=decimal.Decimal('0.00'), help_text='APR percentage, e.g. 5.25', max_digits=7, validators=[MinValueValidator(decimal.Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('regular_payment', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=16, validators=[MinValueValidator(decimal.Decimal('0.00'))])),
                ('payment_day', models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(31)])),
                ('notes', models.TextField(blank=True)),
                ('account', models.OneToOneField(limit_choices_to={'account_type':'loan'}, on_delete=django.db.models.deletion.CASCADE, related_name='loan_profile', to='finance.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('transaction_kind', models.CharField(choices=[('income','Income'),('expense','Expense'),('transfer','Transfer'),('savings','Savings'),('release','Restricted-funds release'),('debt','Debt payment'),('adjustment','Balance adjustment'),('other','Other')], max_length=12)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[MinValueValidator(decimal.Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('weekly','Weekly'),('monthly','Monthly'),('yearly','Yearly')], default='monthly', max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(24)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run', models.DateField()),
                ('auto_post', models.BooleanField(default=False)),
                ('budget_impacts', models.JSONField(blank=True, default=list, help_text='List of {kind, category_id, amount_mode, amount, month_shift}.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_outgoing', to='finance.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='finance.household')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_incoming', to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_type', models.CharField(choices=[('contains','Contains'),('starts','Starts with'),('exact','Exact'),('regex','Regular expression')], default='contains', max_length=10)),
                ('pattern', models.CharField(max_length=240)),
                ('direction', models.CharField(choices=[('any','Any'),('in','Money in'),('out','Money out')], default='any', max_length=3)),
                ('transaction_kind', models.CharField(blank=True, choices=[('income','Income'),('expense','Expense'),('transfer','Transfer'),('savings','Savings'),('release','Restricted-funds release'),('debt','Debt payment'),('adjustment','Balance adjustment'),('other','Other')], max_length=12)),
                ('impact_kind', models.CharField(blank=True, choices=[('funding','Funding available'),('expense','Expense'),('savings','Savings allocation')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_rules', to='finance.household')),
            ],
            options={'ordering':['priority','name']},
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('delimiter', models.CharField(default=',', max_length=4)),
                ('encoding', models.CharField(default='utf-8-sig', max_length=30)),
                ('date_column', models.CharField(max_length=120)),
                ('description_column', models.CharField(max_length=120)),
                ('amount_column', models.CharField(blank=True, max_length=120)),
                ('debit_column', models.CharField(blank=True, max_length=120)),
                ('credit_column', models.CharField(blank=True, max_length=120)),
                ('date_format', models.CharField(default='%d.%m.%Y', max_length=40)),
                ('decimal_separator', models.CharField(default=',', max_length=1)),
                ('thousands_separator', models.CharField(default='.', max_length=1)),
                ('invert_sign', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_profiles', to='finance.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_profiles', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to='imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('uploaded','Uploaded'),('parsed','Parsed'),('imported','Imported'),('failed','Failed')], default='uploaded', max_length=10)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='finance.household')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.importprofile')),
            ],
            options={'ordering':['-created_at']},
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Signed: positive into selected bank account.', max_digits=16, null=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_data', models.JSONField(default=dict)),
                ('suggested_kind', models.CharField(blank=True, choices=[('income','Income'),('expense','Expense'),('transfer','Transfer'),('savings','Savings'),('release','Restricted-funds release'),('debt','Debt payment'),('adjustment','Balance adjustment'),('other','Other')], max_length=12)),
                ('suggested_impact_kind', models.CharField(blank=True, choices=[('funding','Funding available'),('expense','Expense'),('savings','Savings allocation')], max_length=10)),
                ('status', models.CharField(choices=[('pending','Pending'),('duplicate','Duplicate'),('imported','Imported'),('error','Error'),('skipped','Skipped')], default='pending', max_length=10)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='finance.importbatch')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='finance.transaction')),
            ],
            options={'ordering':['row_number']},
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.account')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering':['-statement_date']},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering':['-created_at']},
        ),
        migrations.AddConstraint(model_name='membership', constraint=models.UniqueConstraint(fields=('household','user'), name='unique_household_user')),
        migrations.AddConstraint(model_name='account', constraint=models.UniqueConstraint(fields=('household','name'), name='unique_account_name_per_household')),
        migrations.AddConstraint(model_name='category', constraint=models.UniqueConstraint(fields=('household','kind','name'), name='unique_category_per_kind')),
        migrations.AddConstraint(model_name='tag', constraint=models.UniqueConstraint(fields=('household','name'), name='unique_tag_per_household')),
        migrations.AddConstraint(model_name='budgetplan', constraint=models.UniqueConstraint(fields=('household','month','category'), name='unique_month_category_budget')),
        migrations.AddConstraint(model_name='importprofile', constraint=models.UniqueConstraint(fields=('household','name'), name='unique_import_profile_name')),
        migrations.AddConstraint(model_name='importrow', constraint=models.UniqueConstraint(fields=('batch','row_number'), name='unique_import_batch_row')),
    ]
